"""Validate search-engine assets produced by the MkDocs build."""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

SITE_ROOT = Path("site")
SITE_URL = "https://faramarzkowsari.github.io/crisis-signal-ai/"
SITEMAP_URL = f"{SITE_URL}sitemap.xml"
REQUIRED_URLS = {
    SITE_URL,
    f"{SITE_URL}author/",
    f"{SITE_URL}doi-strategy/",
    f"{SITE_URL}model-card/",
    f"{SITE_URL}dataset-card/",
    f"{SITE_URL}research-roadmap/",
}


def fail(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def validate_robots() -> None:
    path = SITE_ROOT / "robots.txt"
    if not path.exists():
        fail("site/robots.txt was not generated.")

    content = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    if "User-agent: *" not in content:
        fail("robots.txt does not define the wildcard user agent.")
    if "Allow: /" not in content:
        fail("robots.txt does not allow crawling.")
    if f"Sitemap: {SITEMAP_URL}" not in content:
        fail("robots.txt does not reference the canonical sitemap URL.")
    if "Disallow: /" in content:
        fail("robots.txt blocks the entire project site.")


def validate_sitemap() -> None:
    path = SITE_ROOT / "sitemap.xml"
    if not path.exists():
        fail("site/sitemap.xml was not generated by MkDocs.")

    try:
        root = ET.parse(path).getroot()
    except ET.ParseError as exc:
        fail(f"sitemap.xml is not valid XML: {exc}")

    namespace = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    urls = {
        node.text.strip()
        for node in root.findall(".//sm:loc", namespace)
        if node.text and node.text.strip()
    }

    missing = sorted(REQUIRED_URLS - urls)
    if missing:
        fail("sitemap.xml is missing required URLs:\n- " + "\n- ".join(missing))

    invalid = sorted(url for url in urls if not url.startswith(SITE_URL))
    if invalid:
        fail("sitemap.xml contains URLs outside the canonical site prefix:\n- " + "\n- ".join(invalid))


def validate_html_indexability() -> None:
    html_files = list(SITE_ROOT.rglob("*.html"))
    if not html_files:
        fail("No generated HTML files were found.")

    for path in html_files:
        lowered = path.read_text(encoding="utf-8", errors="ignore").lower()
        if 'content="noindex' in lowered or "content='noindex" in lowered:
            fail(f"Generated page contains a noindex directive: {path}")


def main() -> None:
    validate_robots()
    validate_sitemap()
    validate_html_indexability()
    print("Search indexing assets validated successfully.")
    print(f"robots.txt: {SITE_URL}robots.txt")
    print(f"sitemap.xml: {SITEMAP_URL}")


if __name__ == "__main__":
    main()
